#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

hello_program="$cmd_dir/hello"
goodbye_program="$cmd_dir/goodbye"

echo "Running hello program"
$hello_program || panic "hello program failed"

echo "Running goodbye program"
$goodbye_program || panic "goodbye program failed"
